#!/bin/bash

if [[ "${BASH_SOURCE}" = "${0}" || ! "${1}" =~ ^(mingw(32|64)|msys)$ ]]; then tee <<done

    MSYS2 Shell Switcher 2016.5.1
    Copyright (C) 2016 Renato Silva
    Licensed under public domain

    This script switches between shells without restarting MSYS2. This is done
    by setting the MSYSTEM variable and sourcing /etc/profile, as well as
    ~/.bashrc, for interactive shells.

    Usage: source $(basename "${0}") mingw32|mingw64|msys

done
    if [[ "${BASH_SOURCE}" = "${0}" ]]
        then exit 1
        else return 1
    fi
fi

_current_directory="$(pwd)"
export MSYSTEM="${1^^}"
source /etc/profile
[[ "${-}" = *i* ]] && source ~/.bashrc
cd "${_current_directory}"
unset _current_directory
