
#define IDC_SPLASH_JPG_00 IDC_SPLASH_START + 0
#define IDC_SPLASH_JPG_01 IDC_SPLASH_START + 1
#define IDC_SPLASH_JPG_02 IDC_SPLASH_START + 2
#define IDC_SPLASH_JPG_03 IDC_SPLASH_START + 3
#define IDC_SPLASH_JPG_04 IDC_SPLASH_START + 4
#define IDC_SPLASH_JPG_05 IDC_SPLASH_START + 5
#define IDC_SPLASH_JPG_06 IDC_SPLASH_START + 6
#define IDC_SPLASH_JPG_07 IDC_SPLASH_START + 7
#define IDC_SPLASH_JPG_08 IDC_SPLASH_START + 8
#define IDC_SPLASH_JPG_09 IDC_SPLASH_START + 9
#define IDC_SPLASH_JPG_10 IDC_SPLASH_START + 10
#define IDC_SPLASH_JPG_11 IDC_SPLASH_START + 11
#define IDC_SPLASH_JPG_12 IDC_SPLASH_START + 12
#define IDC_SPLASH_JPG_13 IDC_SPLASH_START + 13
#define IDC_SPLASH_JPG_14 IDC_SPLASH_START + 14
#define IDC_SPLASH_JPG_15 IDC_SPLASH_START + 15
#define IDC_SPLASH_JPG_16 IDC_SPLASH_START + 16
#define IDC_SPLASH_JPG_17 IDC_SPLASH_START + 17
#define IDC_SPLASH_COUNT 18
