post_install() {
 /usr/bin/install-catalog --add \
                      /etc/sgml/dsssl-docbook-stylesheets.cat \
                      /usr/share/sgml/docbook/dsssl-stylesheets-1.79/catalog
 
 /usr/bin/install-catalog --add \
                     /etc/sgml/sgml-docbook.cat \
                     /etc/sgml/dsssl-docbook-stylesheets.cat

}

post_upgrade() {
  post_install $1
}

post_remove() {
  /usr/bin/install-catalog --remove \
                      /etc/sgml/dsssl-docbook-stylesheets.cat \
                      /usr/share/sgml/docbook/dsssl-stylesheets-1.79/catalog
  
  /usr/bin/install-catalog --remove \
                     /etc/sgml/sgml-docbook.cat \
                     /etc/sgml/dsssl-docbook-stylesheets.cat
}
