post_install() {
  cat << _EOF

==> IMPORTANT!!!
==> To prevent overwriting your existing configuration, nanorc
==> was installed to /usr/share/nano-syntax-highlighting/nanorc.sample
==>
==> To install you should add the languages you want to your nano configuration file /etc/nanorc or ~/.nanorc
==> $ cat /usr/share/nano-syntax-highlighting/nanorc.sample | xargs -0 echo >> ~/.nanorc

_EOF
}

post_upgrade() {
  post_install $1
}
