post_install() {
    # Create the make wrapper without overriding make.exe
    echo '#!/bin/bash'                                  > /usr/bin/make.sh
    echo 'COLORMAKE_COMMAND=make.exe colormake "${@}"' >> /usr/bin/make.sh
    /usr/bin/cmd //c "ren $(cygpath -w /usr/bin/make.sh) make"
}

pre_remove() {
    # Remove the make wrapper not make.exe
    /usr/bin/cmd //c "del /q $(cygpath -w /usr/bin/make)"
}
