PYTHON_SITELIB=usr/lib/python2.7/site-packages
PYTHON_LIB=usr/lib/python2.7

python_optimize() {
  local pyd

  for pyd in "${@:-${PYTHON_SITELIB}}"
  do
    if [ ! -d ${pyd} ]
    then
      echo "Error: directory ${pyd} does not exist"
    fi

    echo "Compiling ${pyd}..."
    usr/bin/python2 ${PYTHON_LIB}/compileall.py -f -q -d ${pyd} ${pyd}
    usr/bin/python2 -OO ${PYTHON_LIB}/compileall.py -f -q -d ${pyd} ${pyd}
  done
}

post_install() {
  python_optimize
}
