info_dir=usr/share/info
info_files="gmp.info gmp.info-1 gmp.info-2"

post_install() {
  [ -x usr/bin/install-info ] || return 0
  for f in ${info_files}; do
    install-info ${info_dir}/$f.gz ${info_dir}/dir 2> /dev/null
  done
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  [ -x usr/bin/install-info ] || return 0
  for f in ${info_files}; do
    install-info --delete ${info_dir}/$f.gz ${info_dir}/dir 2> /dev/null
  done
}
