infodir=usr/share/info
filelist=(zsh.info zsh.info-1 zsh.info-2 zsh.info-3 zsh.info-4 zsh.info-5 zsh.info-6)

post_install() {
	[ -x usr/bin/install-info ] || return 0
	for file in ${filelist[@]}; do
		install-info $infodir/$file.gz $infodir/dir 2> /dev/null
	done
}

post_upgrade() {
	post_install
}

pre_remove() {
	[ -x usr/bin/install-info ] || return 0
	for file in ${filelist[@]}; do
		install-info --delete $infodir/$file.gz $infodir/dir 2> /dev/null
	done
}
