post_install() {
  echo ""
  echo "This package does not set itself up automatically."
  echo "Go to /usr/lib/taskd/taskd.notes to for the original Arch Linux information."
  echo "Included is the Arch Linux taskd.service, conf.d, and taskd.install"
  echo "Go to /usr/lib/taskd/pki/ to generate certificates."
  echo "You must create the MSYS2 daemon scripts yourself."
  echo "Submit a pull request or contact the maintainer of this package."
}


post_upgrade() {
  post_install
}
